; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:atlas]
platform = espressif32
board = esp32dev
framework = arduino

build_src_filter = 
    +<atlas/>
    +<common/>
    +<uart/>
    +<protocol/>
    +<transport/>

monitor_speed = 115200
monitor_eol = CRLF

[env:firefly]
platform = espressif32
board = esp32dev
framework = arduino

build_src_filter =
    +<firefly/>
    +<common/>
    +<uart/>
    +<protocol/>
    +<transport/>

monitor_speed = 115200

[env:atlas_espnow]
platform = espressif32
board = esp32dev
framework = arduino

build_flags = 
    -DNEXUS_ROLE_ATLAS

build_src_filter = 
    +<atlas/>
    +<common/>
    +<espnow/>
    +<protocol/>
    +<transport/>
    -<transport/UartTransport.cpp>

monitor_speed = 115200
monitor_eol = CRLF

[env:firefly_espnow]
platform = espressif32
board = esp32dev
framework = arduino

build_flags = 
    -DNEXUS_ROLE_FIREFLY

build_src_filter =
    +<firefly/>
    +<common/>
    +<espnow/>
    +<protocol/>
    +<transport/>
    -<transport/UartTransport.cpp>

monitor_speed = 115200